import type { ProductAttribute } from "../../../schemas/product-schema";
import type { EditableVariation } from "../../../hooks/useVariationManager";

// ============================================================================
// MOCK ATTRIBUTES
// ============================================================================

export const MOCK_ATTRIBUTES: ProductAttribute[] = [
    {
        id: 1,
        name: "Boîte de vitesse",
        options: ["Boîte manuelle", "Palettes au volant", "Couture rouge"],
        visible: true,
        variation: true,
        position: 0,
    },
    {
        id: 2,
        name: "Couleur",
        options: ["Noir", "Blanc", "Bleu"],
        visible: true,
        variation: true,
        position: 1,
    },
    {
        id: 3,
        name: "Taille",
        options: ["S", "M", "L"],
        visible: true,
        variation: true,
        position: 2,
    },
];

// ============================================================================
// MOCK VARIATIONS
// ============================================================================

const makeDimensions = () => ({ length: "", width: "", height: "" });

// Each variation = ONE unique combination of ALL variation attributes (flat, no hierarchy).
// Per WooCommerce API: variation.attributes[] picks ONE option from EACH product attribute.
export const MOCK_VARIATIONS: EditableVariation[] = [
    {
        _localId: "v1",
        _status: "synced",
        dbId: "db-v1",
        sku: "BV-MAN-N-M",
        regularPrice: "300",
        salePrice: "",
        stockQuantity: 2,
        manageStock: true,
        stockStatus: "instock",
        weight: "1.5",
        dimensions: makeDimensions(),
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Boîte de vitesse", option: "Boîte manuelle" },
            { name: "Couleur", option: "Noir" },
            { name: "Taille", option: "M" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "3760123456789",
        backorders: "no" as const,
        taxStatus: "taxable" as const,
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
    {
        _localId: "v2",
        _status: "synced",
        dbId: "db-v2",
        sku: "BV-MAN-B-L",
        regularPrice: "310",
        salePrice: "289.99",
        stockQuantity: 3,
        manageStock: true,
        stockStatus: "instock",
        weight: "1.2",
        dimensions: makeDimensions(),
        description: "Édition spéciale",
        status: "publish",
        image: null,
        attributes: [
            { name: "Boîte de vitesse", option: "Boîte manuelle" },
            { name: "Couleur", option: "Blanc" },
            { name: "Taille", option: "L" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "3760987654321",
        backorders: "no" as const,
        taxStatus: "taxable" as const,
        taxClass: "",
        dateOnSaleFrom: "2026-02-01",
        dateOnSaleTo: "2026-03-31",
    },
    {
        _localId: "v3",
        _status: "synced",
        dbId: "db-v3",
        sku: "BV-PAL-B-M",
        regularPrice: "369.99",
        salePrice: "",
        stockQuantity: 1,
        manageStock: true,
        stockStatus: "instock",
        weight: "",
        dimensions: makeDimensions(),
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Boîte de vitesse", option: "Palettes au volant" },
            { name: "Couleur", option: "Blanc" },
            { name: "Taille", option: "M" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "no" as const,
        taxStatus: "taxable" as const,
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
    {
        _localId: "v4",
        _status: "modified",
        dbId: "db-v4",
        sku: "BV-PAL-N-S",
        regularPrice: "379.99",
        salePrice: "",
        stockQuantity: 1,
        manageStock: true,
        stockStatus: "instock",
        weight: "",
        dimensions: makeDimensions(),
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Boîte de vitesse", option: "Palettes au volant" },
            { name: "Couleur", option: "Noir" },
            { name: "Taille", option: "S" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "no" as const,
        taxStatus: "taxable" as const,
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
    {
        _localId: "v5",
        _status: "new",
        sku: "BV-COU-BL-L",
        regularPrice: "399",
        salePrice: "",
        stockQuantity: 5,
        manageStock: true,
        stockStatus: "instock",
        weight: "",
        dimensions: makeDimensions(),
        description: "",
        status: "draft",
        image: null,
        attributes: [
            { name: "Boîte de vitesse", option: "Couture rouge" },
            { name: "Couleur", option: "Bleu" },
            { name: "Taille", option: "L" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "no" as const,
        taxStatus: "taxable" as const,
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
    {
        _localId: "v6",
        _status: "synced",
        dbId: "db-v6",
        sku: "BV-COU-N-S",
        regularPrice: "389",
        salePrice: "349.99",
        stockQuantity: 2,
        manageStock: true,
        stockStatus: "instock",
        weight: "",
        dimensions: makeDimensions(),
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Boîte de vitesse", option: "Couture rouge" },
            { name: "Couleur", option: "Noir" },
            { name: "Taille", option: "S" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "no" as const,
        taxStatus: "taxable" as const,
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
];

// ============================================================================
// MOCK FORM DEFAULT VALUES (for FormProvider)
// ============================================================================

export const MOCK_FORM_DEFAULTS = {
    title: "Produit démo - Variable",
    sku: "DEMO-VAR",
    global_unique_id: "",
    short_description: "",
    description: "",
    permalink: null,
    regular_price: "",
    sale_price: "",
    on_sale: false,
    date_on_sale_from: "",
    date_on_sale_to: "",
    stock: "",
    stock_status: "instock" as const,
    manage_stock: false,
    backorders: "no" as const,
    low_stock_amount: "",
    meta_title: "",
    meta_description: "",
    slug: "produit-demo",
    product_type: "variable",
    brand: "",
    status: "draft",
    featured: false,
    categories: [],
    tags: [],
    images: [],
    weight: "",
    dimensions_length: "",
    dimensions_width: "",
    dimensions_height: "",
    shipping_class: "",
    tax_status: "taxable" as const,
    tax_class: "",
    catalog_visibility: "visible" as const,
    virtual: false,
    downloadable: false,
    purchasable: true,
    external_url: "",
    button_text: "",
    sold_individually: false,
    purchase_note: "",
    menu_order: 0,
    reviews_allowed: true,
    average_rating: null,
    rating_count: null,
    total_sales: null,
    upsell_ids: [],
    cross_sell_ids: [],
    related_ids: [],
    attributes: MOCK_ATTRIBUTES,
};
