import type { EditableVariation } from "@/features/products/hooks/useVariationManager";
import type { ProductFormValues } from "@/features/products/schemas/product-schema";

export const MOCK_VARIATIONS: EditableVariation[] = [
    {
        _localId: "var-1",
        _status: "synced",
        dbId: "db-uuid-1",
        externalId: "101",
        sku: "PROD-BLU-S",
        regularPrice: "29.99",
        salePrice: "",
        stockQuantity: 15,
        manageStock: true,
        stockStatus: "instock",
        weight: "0.3",
        dimensions: { length: "10", width: "5", height: "2" },
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Couleur", option: "Bleu" },
            { name: "Taille", option: "S" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "no",
        taxStatus: "taxable",
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
    {
        _localId: "var-2",
        _status: "synced",
        dbId: "db-uuid-2",
        externalId: "102",
        sku: "PROD-BLU-M",
        regularPrice: "29.99",
        salePrice: "24.99",
        stockQuantity: 8,
        manageStock: true,
        stockStatus: "instock",
        weight: "0.3",
        dimensions: { length: "10", width: "5", height: "2" },
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Couleur", option: "Bleu" },
            { name: "Taille", option: "M" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "no",
        taxStatus: "taxable",
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
    {
        _localId: "var-3",
        _status: "modified",
        dbId: "db-uuid-3",
        externalId: "103",
        sku: "PROD-RED-S",
        regularPrice: "34.99",
        salePrice: "",
        stockQuantity: 0,
        manageStock: true,
        stockStatus: "outofstock",
        weight: "0.3",
        dimensions: { length: "10", width: "5", height: "2" },
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Couleur", option: "Rouge" },
            { name: "Taille", option: "S" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "notify",
        taxStatus: "taxable",
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
    {
        _localId: "var-4",
        _status: "new",
        sku: "PROD-RED-M",
        regularPrice: "34.99",
        salePrice: "",
        stockQuantity: null,
        manageStock: false,
        stockStatus: "instock",
        weight: "",
        dimensions: { length: "", width: "", height: "" },
        description: "",
        status: "publish",
        image: null,
        attributes: [
            { name: "Couleur", option: "Rouge" },
            { name: "Taille", option: "M" },
        ],
        virtual: false,
        downloadable: false,
        globalUniqueId: "",
        backorders: "no",
        taxStatus: "taxable",
        taxClass: "",
        dateOnSaleFrom: "",
        dateOnSaleTo: "",
    },
];

export const MOCK_FORM_DEFAULTS: Partial<ProductFormValues> = {
    title: "T-Shirt Premium Collection",
    sku: "PROD-PARENT",
    short_description: "<p>T-shirt de qualité premium disponible en plusieurs couleurs et tailles.</p>",
    description: "<p>Notre t-shirt premium est fabriqué en coton biologique de haute qualité...</p>",
    regular_price: "29.99",
    sale_price: null,
    stock: null,
    manage_stock: false,
    stock_status: "instock",
    type: "variable",
    status: "publish",
};
