/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOverviewRouteImport } from './routes/app/overview'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppStoresIndexRouteImport } from './routes/app/stores/index'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppBlogIndexRouteImport } from './routes/app/blog/index'
import { Route as AppBlogFlowriterRouteImport } from './routes/app/blog/flowriter'
import { Route as AppProductsProductIdEditRouteImport } from './routes/app/products/$productId/edit'
import { Route as AppBlogEditorNewRouteImport } from './routes/app/blog/editor/new'
import { Route as AppBlogEditorArticleIdRouteImport } from './routes/app/blog/editor/$articleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresIndexRoute = AppStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogFlowriterRoute = AppBlogFlowriterRouteImport.update({
  id: '/blog/flowriter',
  path: '/blog/flowriter',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdEditRoute =
  AppProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppBlogEditorNewRoute = AppBlogEditorNewRouteImport.update({
  id: '/blog/editor/new',
  path: '/blog/editor/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogEditorArticleIdRoute = AppBlogEditorArticleIdRouteImport.update({
  id: '/blog/editor/$articleId',
  path: '/blog/editor/$articleId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/': typeof AppIndexRoute
  '/app/blog/flowriter': typeof AppBlogFlowriterRoute
  '/app/blog/': typeof AppBlogIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/stores/': typeof AppStoresIndexRoute
  '/app/blog/editor/$articleId': typeof AppBlogEditorArticleIdRoute
  '/app/blog/editor/new': typeof AppBlogEditorNewRoute
  '/app/products/$productId/edit': typeof AppProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/overview': typeof AppOverviewRoute
  '/app': typeof AppIndexRoute
  '/app/blog/flowriter': typeof AppBlogFlowriterRoute
  '/app/blog': typeof AppBlogIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/stores': typeof AppStoresIndexRoute
  '/app/blog/editor/$articleId': typeof AppBlogEditorArticleIdRoute
  '/app/blog/editor/new': typeof AppBlogEditorNewRoute
  '/app/products/$productId/edit': typeof AppProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/': typeof AppIndexRoute
  '/app/blog/flowriter': typeof AppBlogFlowriterRoute
  '/app/blog/': typeof AppBlogIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/stores/': typeof AppStoresIndexRoute
  '/app/blog/editor/$articleId': typeof AppBlogEditorArticleIdRoute
  '/app/blog/editor/new': typeof AppBlogEditorNewRoute
  '/app/products/$productId/edit': typeof AppProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/overview'
    | '/app/'
    | '/app/blog/flowriter'
    | '/app/blog/'
    | '/app/products/'
    | '/app/stores/'
    | '/app/blog/editor/$articleId'
    | '/app/blog/editor/new'
    | '/app/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/dashboard'
    | '/app/overview'
    | '/app'
    | '/app/blog/flowriter'
    | '/app/blog'
    | '/app/products'
    | '/app/stores'
    | '/app/blog/editor/$articleId'
    | '/app/blog/editor/new'
    | '/app/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/overview'
    | '/app/'
    | '/app/blog/flowriter'
    | '/app/blog/'
    | '/app/products/'
    | '/app/stores/'
    | '/app/blog/editor/$articleId'
    | '/app/blog/editor/new'
    | '/app/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stores/': {
      id: '/app/stores/'
      path: '/stores'
      fullPath: '/app/stores/'
      preLoaderRoute: typeof AppStoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/': {
      id: '/app/blog/'
      path: '/blog'
      fullPath: '/app/blog/'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/flowriter': {
      id: '/app/blog/flowriter'
      path: '/blog/flowriter'
      fullPath: '/app/blog/flowriter'
      preLoaderRoute: typeof AppBlogFlowriterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/$productId/edit': {
      id: '/app/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/app/products/$productId/edit'
      preLoaderRoute: typeof AppProductsProductIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/editor/new': {
      id: '/app/blog/editor/new'
      path: '/blog/editor/new'
      fullPath: '/app/blog/editor/new'
      preLoaderRoute: typeof AppBlogEditorNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blog/editor/$articleId': {
      id: '/app/blog/editor/$articleId'
      path: '/blog/editor/$articleId'
      fullPath: '/app/blog/editor/$articleId'
      preLoaderRoute: typeof AppBlogEditorArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBlogFlowriterRoute: typeof AppBlogFlowriterRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppStoresIndexRoute: typeof AppStoresIndexRoute
  AppBlogEditorArticleIdRoute: typeof AppBlogEditorArticleIdRoute
  AppBlogEditorNewRoute: typeof AppBlogEditorNewRoute
  AppProductsProductIdEditRoute: typeof AppProductsProductIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppIndexRoute: AppIndexRoute,
  AppBlogFlowriterRoute: AppBlogFlowriterRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppStoresIndexRoute: AppStoresIndexRoute,
  AppBlogEditorArticleIdRoute: AppBlogEditorArticleIdRoute,
  AppBlogEditorNewRoute: AppBlogEditorNewRoute,
  AppProductsProductIdEditRoute: AppProductsProductIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
