export interface WooCommerceProduct {
    id: number;
    name: string;
    slug: string;
    permalink: string;
    description: string;
    short_description: string;
    type: string;
    status: string;
    featured: boolean;
    catalog_visibility: string;
    sku: string;
    global_unique_id: string;
    price: string;
    regular_price: string;
    sale_price: string;
    date_on_sale_from: string | null;
    date_on_sale_from_gmt: string | null;
    date_on_sale_to: string | null;
    date_on_sale_to_gmt: string | null;
    price_html: string;
    on_sale: boolean;
    purchasable: boolean;
    total_sales: number;
    virtual: boolean;
    downloadable: boolean;
    downloads: Array<{ id: string; name: string; file: string }>;
    download_limit: number;
    download_expiry: number;
    external_url: string;
    button_text: string;
    tax_status: string;
    tax_class: string;
    manage_stock: boolean;
    stock_quantity: number | null;
    stock_status: string;
    backorders: string;
    backorders_allowed: boolean;
    backordered: boolean;
    sold_individually: boolean;
    weight: string;
    dimensions: { length: string; width: string; height: string };
    shipping_required: boolean;
    shipping_taxable: boolean;
    shipping_class: string;
    shipping_class_id: number;
    reviews_allowed: boolean;
    average_rating: string;
    rating_count: number;
    related_ids: number[];
    upsell_ids: number[];
    cross_sell_ids: number[];
    parent_id: number;
    purchase_note: string;
    categories: Array<{ id: number; name: string; slug: string }>;
    tags: Array<{ id: number; name: string; slug: string }>;
    images: Array<{
        id: number;
        src: string;
        name: string;
        alt: string;
        date_created: string;
        date_created_gmt: string;
        date_modified: string;
        date_modified_gmt: string;
    }>;
    attributes: Array<{
        id: number;
        name: string;
        position: number;
        visible: boolean;
        variation: boolean;
        options: string[];
    }>;
    default_attributes: Array<{
        id: number;
        name: string;
        option: string;
    }>;
    variations: number[];
    grouped_products: number[];
    menu_order: number;
    date_created: string;
    date_created_gmt: string;
    date_modified: string;
    date_modified_gmt: string;
    meta_data?: Array<{ key: string; value: any }>;
}

export interface WooCommerceVariation {
    id: number;
    sku: string;
    permalink?: string;
    status?: 'draft' | 'pending' | 'private' | 'publish';
    description?: string;
    price: string;
    regular_price: string;
    sale_price: string;
    on_sale?: boolean;
    purchasable?: boolean;
    date_on_sale_from?: string | null;
    date_on_sale_from_gmt?: string | null;
    date_on_sale_to?: string | null;
    date_on_sale_to_gmt?: string | null;
    stock_quantity: number | null;
    manage_stock: boolean | 'parent';
    stock_status: string;
    backorders?: 'no' | 'notify' | 'yes';
    backorders_allowed?: boolean;
    backordered?: boolean;
    low_stock_amount?: number | null;
    weight: string;
    dimensions: { length: string; width: string; height: string };
    shipping_class?: string;
    shipping_class_id?: number;
    tax_status?: 'taxable' | 'shipping' | 'none';
    tax_class?: string;
    virtual?: boolean;
    downloadable?: boolean;
    downloads?: Array<{
        id: string;
        name: string;
        file: string;
    }>;
    download_limit?: number;
    download_expiry?: number;
    image: {
        id: number;
        src: string;
        name: string;
        alt: string;
        date_created?: string;
        date_created_gmt?: string;
        date_modified?: string;
        date_modified_gmt?: string;
    } | null;
    attributes: Array<{
        id: number;
        name: string;
        option: string;
    }>;
    menu_order?: number;
    date_created: string;
    date_created_gmt: string;
    date_modified: string;
    date_modified_gmt: string;
    meta_data?: Array<{
        id?: number;
        key: string;
        value: any;
    }>;
}

export interface WooCommerceReview {
    id: number;
    date_created: string;
    date_created_gmt: string;
    rating: number;
    reviewer: string;
    reviewer_email: string;
    review: string;
    verified: boolean;
    status: string;
}
